services:
  - type: web
    name: sync-frontend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash
      - key: BACKEND_URL
        fromService:
          name: sync-backend
          type: web
          property: url
      # NEXT_PUBLIC_BASE_URL will be available implicitly at runtime via RENDER_EXTERNAL_URL.
      # If you prefer explicit env, uncomment the following and set a dummy default; Render will override with the actual URL via property above if needed.
      # - key: NEXT_PUBLIC_BASE_URL
      #   fromService:
      #     name: sync-frontend
      #     type: web
      #     property: url

  - type: web
    name: sync-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          name: sync-frontend
          type: web
          property: url
